[package]
name = "game-comms-client"
version = "0.1.0"
authors = ["Tiaan Louw <tiaanl@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
